# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1
    instance:
      data:
        enabled: true
    s3:
      endpoint: https://s3.ap-northeast-1.amazonaws.com